### ISSUE TITLE
这套框架是基于什么前端框架的？

### ISSUE THREAD

**Issue by sunfaces** [herozhou/vue-framework-wz#1]
除了vuejs之外，说实话，没太看得出来，好像风格跟coreui.io挺像的

**Comment by sunfaces** [comment]
蛮好看的，就是希望能知道具体用到的前端ui框架，这样在这个基础上做二次开发也比较有底，目前看来有iview和bootstrap？

**Comment by herozhou** [comment]
为了简化体积 全部采用了iview，bootstrap部分已经删除了
