### ISSUE TITLE
怎么使用axios发送ajax请求

### ISSUE THREAD

**Issue by 451729494** [herozhou/vue-framework-wz#11]
现在前端已经可以独立跑起来了，我看了源码，你对axios进行了一层封装，怎么才能调用到你封装的axios实现请求后台

**Comment by herozhou** [comment]
可以直接使用jQuery的$.post发送请求，如果使用axios，可以去看下文档 [https://github.com/axios/axios](https://github.com/axios/axios)

**Comment by usering1995** [comment]
@/utils/fetch可以调用吗？

**Comment by wuquaner** [comment]
需要先安装axios才能使用
安装axios:  npm install axios --save

**Comment by usering1995** [comment]
下了！
@/utils/fetch
@/utils/fhttp
是不是都得引入？

**Comment by usering1995** [comment]
下了
@/utils/fetch
@/utils/http
是不是都得引入
