### ISSUE TITLE
npm ls iview 查看包的信息，发现vuejs有问题，故修改package.json 的vuejs的版本

### ISSUE THREAD

**Issue by wwb568109135** [herozhou/vue-framework-wz#17]
WZ@1.0.0 /Users/jerry/demo/vue-framework-wz
└── UNMET PEER DEPENDENCY vue@2.3.3

npm ERR! peer dep missing: vue@^2.5.2, required by iview@2.6.0
npm ERR! code 1

ps:不知道你这边升级了vuejs的版本后，企业东西会不会有问题，gg！

更新一下 vue-template-compiler 的版本 @2.5.2

**Comment by herozhou** [comment]
OK，感谢感谢
