### ISSUE TITLE
dashboard 在pc的谷歌模拟器下面，页面UI显示有bug，同理，在其它页面上存在这个问题

### ISSUE THREAD

**Issue by wwb568109135** [herozhou/vue-framework-wz#18]
dashboard 页面显示Ui的bug图：
![image](https://user-images.githubusercontent.com/5113679/32261445-84b12e1c-bf09-11e7-86f0-baca37421ea0.png)

描述：dashboard 在pc的谷歌模拟器下面，页面UI显示有bug，同理，在其它页面上存在这个问题

楼主这个业务，赞

**Comment by herozhou** [comment]
适配没有做那么精细，最近比较忙，等有时间再修改
