### ISSUE TITLE
npm 提示缺少js-beautify文件

### ISSUE THREAD

**Issue by 1011cat** [herozhou/vue-framework-wz#2]
npm 提示缺少js-beautify文件

**Comment by herozhou** [comment]
是不是npm 版本太低了？
你贴下报错图片以及npm 版本
使用一下命令查看npm  版本号
```
npm -v
```

**Comment by 1011cat** [comment]
公司window npm正常的  家里mac npm也是最新的.不知道为什么会有这个问题.
初学vue2,准备把公司以前jsp写的管理重构成vue2.这个框架对我现在很有用!想提一个小小的需求,我发现基本所有的ui和框架都没提供右键菜单栏这个功能.好吧,我司就有这样的需求,找了下,只能vue自己封装一个,或者引入jquery,使用右键插件.
其实很多列表是使用右键直接选择编辑,删除添加操作.用途还是很广的.最后还是谢谢!这个框架还是很不错的!!!加油!

**Comment by herozhou** [comment]
这个建议很好，会抽空尝试一下能否增加。现在还是解决一下你的npm 报错问题，截图能给我看一下吗？

**Comment by 1011cat** [comment]
我现在在公司,家里的电脑不在身边,我下班回去了再试下,不行,我再截图给你

**Comment by 1011cat** [comment]
我刚刚修改时,发现一个问题,左侧导航栏,如果点开的项目超过屏幕高度就会出现一个黑色的滚动条,,太扎眼睛了.

**Comment by herozhou** [comment]
其实我觉得还行，个人审美太差了😂。
我已经把它删除了，是这几个css类控制的，你可以根据个人需要更改或删除

```
.sidebar .sidebar-nav::-webkit-scrollbar {
  }
.sidebar .sidebar-nav::-webkit-scrollbar-thumb{
}
.sidebar .sidebar-nav::-webkit-scrollbar-track{
}
```

**Comment by 1011cat** [comment]
非常感谢  现在还在改样式,  往head里面加li 准备加导航.其实我审美也就那样.只是觉得改成同色比较好.

**Comment by 1011cat** [comment]
我发邮件 加wx 私聊吧  我也刚接触vue2  看代码还有的地方疑惑.谢谢!!

**Comment by herozhou** [comment]
好的，有什么问题随时问我
