### ISSUE TITLE
关于路由列表,我想请教一下

### ISSUE THREAD

**Issue by dearfriendz** [herozhou/vue-framework-wz#21]
如果不用做鉴权的,只需要发送请求后台验证登录的跳转应该怎么写呢,关于您写的有点复杂有点看不懂,不过功能一定可以实现

**Comment by herozhou** [comment]
把路由列表里的 ```meta``` 字段去掉就ok

**Comment by dearfriendz** [comment]
但是我在搜索meta的时候是没有找到的
