### ISSUE TITLE
项目使用

### ISSUE THREAD

**Issue by caoanqi** [herozhou/vue-framework-wz#5]
很不错的项目，本人对vue不了接，请问是否为本人项目，是否可做商用？谢谢

**Comment by herozhou** [comment]
MIT License

MIT是和BSD一样宽松的许可协议,作者只想保留版权,而无任何其他了限制.也就是说,你必须在你的发行版里包含原许可协议的声明,无论你是以二进制发布的还是以源代码发布的。

* 你可以使用，复制和修改软件
* 你可以免费使用软件或出售
* 唯一的限制是，它是必须附有MIT授权协议


________________________________
发件人: jerry <notifications@github.com>
发送时间: 2017年9月20日 7:36
收件人: herozhou/vue-framework-wz
抄送: Subscribed
主题: [herozhou/vue-framework-wz] 项目使用 (#5)


请问是否为本人项目，是否可做商用？谢谢

―
