### ISSUE TITLE
Tinymce.vue找不到问题

### ISSUE THREAD

**Issue by morgeq** [herozhou/vue-framework-wz#84]
ERROR  Failed to compile with 1 errors                                                                                                                                                                                            5:51:41 PM

This dependency was not found:

* vue-tinymce in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Tinymce.vue

To install it, you can run: npm install --save vue-tinymce

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by loveyeguo** [comment]
我遇到一样的问题 为什么没有人解决？

**Comment by feikalieluofa** [comment]
解决了嘛兄弟

**Comment by rangewr** [comment]
1.package.json文件中找相关的依赖并删除
2.dos窗口删除依赖npm uninstall vue-tinymce
3.重新下载npm install vue-tinymce

**Comment by lpreterite** [comment]
这个项目引用的vue-tinymce是我写的那个库啦，需要重新安装。

```sh
npm i -S lpreterite/vue-tinymce
```
