### ISSUE TITLE
登录页在手机浏览器上体验较差

### ISSUE THREAD

**Issue by qq57941500** [herozhou/vue-framework-wz#9]
感谢大神发布Vue后台管理框架！看起来真不错！
我尝试用手机（安卓）来打开登录页，发现有两个问题：
1. 竖屏状态下登录框显示不全
2. 点击输入框后不弹出键盘，无法输入用户名密码
当然，这种后台管理系统可以不考虑手机端。但是我觉得体验可以差点，但功能应该还是好用的。所以，希望至少能fix第二个问题

**Comment by herozhou** [comment]
谢谢你。已经修复了第二个bug,第一个bug吃完饭就改。Thanks~
